function Jeps = Jeps(Ts,nu,tau,theta)
nu1=nu(1);
nu2=nu(2);
nu3=nu(3);
tau1=tau(1);
tau2=tau(2);
tau3=tau(3);
theta1=theta(1);
theta2=theta(2);
theta3=theta(3);
theta4=theta(4);
theta5=theta(5);
theta6=theta(6);
theta7=theta(7);
theta8=theta(8);

%JEPS
%    JEPS = JEPS(TS,NU1,NU2,NU3,TAU1,TAU2,TAU3,THETA1,THETA2,THETA3,THETA4,THETA5,THETA6,THETA7,THETA8)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    23-May-2016 14:23:35

t2 = 1.0./theta1;
t3 = theta2.*theta4;
t4 = theta3.^2;
t5 = t3-t4;
t6 = 1.0./t5;
t7 = 1.0./t5.^2;
t8 = nu2.*theta2;
t9 = nu3.*theta3;
t10 = t8+t9;
t11 = nu1.*nu2.*t6.*theta3;
t12 = nu2.*theta7;
t13 = nu3.*theta8;
t14 = nu1.*t10;
t16 = nu1.*nu2.*theta1;
t15 = t12+t13+t14-t16-tau3;
t17 = nu2.*theta6;
t18 = nu3.*theta7;
t19 = nu1.*nu3.*theta1;
t20 = t17+t18+t19-tau2;
t21 = nu1.*nu3.*t6.*theta3;
t22 = t6.*t15;
t23 = nu1.*nu2.*t6.*theta2;
t24 = t6.*t20;
Jeps = reshape([Ts.*1.0./theta1.^2.*(tau1+nu3.*t10-nu1.*theta5),Ts.*(t11+nu1.*nu3.*t6.*theta4),-Ts.*(t21+t23),-Ts.*nu2.*nu3.*t2,-Ts.*(t11+t7.*t20.*theta4.^2-t7.*t15.*theta3.*theta4),Ts.*(t22+t23-t7.*t15.*theta2.*theta4+t7.*t20.*theta3.*theta4),-Ts.*nu3.^2.*t2,-Ts.*(t21+t22+t4.*t7.*t15.*2.0-t7.*t20.*theta3.*theta4.*2.0),-Ts.*(t24+t4.*t7.*t20.*2.0-nu1.*nu3.*t6.*theta2-t7.*t15.*theta2.*theta3.*2.0),0.0,Ts.*(t24+t7.*t15.*theta2.*theta3-t7.*t20.*theta2.*theta4),-Ts.*(t7.*t15.*theta2.^2-t7.*t20.*theta2.*theta3),Ts.*nu1.*t2,0.0,0.0,0.0,Ts.*nu2.*t6.*theta4,-Ts.*nu2.*t6.*theta3,0.0,-Ts.*(nu2.*t6.*theta3-nu3.*t6.*theta4),Ts.*(nu2.*t6.*theta2-nu3.*t6.*theta3),0.0,-Ts.*nu3.*t6.*theta3,Ts.*nu3.*t6.*theta2],[3,8]);
