function nudot = Nudot(nu,tau,theta)
[m,d]=Theta2Matrices(theta);
%NUDOT
%    OUTPUT = NUDOT

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-May-2016 21:47:24

t2 = nu(3.0);
t3 = m(2.0,2.0);
t4 = m(3.0,3.0);
t5 = m(2.0,3.0);
t6 = nu(2.0);
t7 = nu(1.0);
t8 = m(1.0,1.0);
t9 = t3.*t4;
t10 = t5.^2;
t11 = t9-t10;
t12 = 1.0./t11;
t13 = d(2.0,3.0);
t14 = t3.*t6;
t15 = t2.*t5;
t16 = t14+t15;
t17 = tau(2.0);
t18 = d(2.0,2.0);
t19 = t6.*t18;
t20 = t2.*t13;
t21 = t2.*t7.*t8;
t22 = -t17+t19+t20+t21;
t23 = tau(3.0);
t24 = t6.*t13;
t25 = d(3.0,3.0);
t26 = t2.*t25;
t27 = t7.*t16;
t28 = -t23+t24+t26+t27-t6.*t7.*t8;
nudot= [(tau(1.0)-t7.*d(1.0,1.0)+t2.*t16)./t8;-t4.*t12.*t22+t5.*t12.*t28;t5.*t12.*t22-t3.*t12.*t28];
