function Output = SystemOutput(Ts,nu,tau,theta)
[m,d]=Theta2Matrices(theta);
%SYSTEMOUTPUT
%    OUTPUT = SYSTEMOUTPUT(TS)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    19-May-2016 21:47:23

t2 = nu(1.0);
t3 = nu(3.0);
t4 = nu(2.0);
t5 = m(2.0,2.0);
t6 = m(3.0,3.0);
t7 = m(2.0,3.0);
t8 = m(1.0,1.0);
t9 = t5.*t6;
t10 = t7.^2;
t11 = t9-t10;
t12 = 1.0./t11;
t13 = d(2.0,3.0);
t14 = t4.*t5;
t15 = t3.*t7;
t16 = t14+t15;
t17 = tau(2.0);
t18 = d(2.0,2.0);
t19 = t4.*t18;
t20 = t3.*t13;
t21 = t2.*t3.*t8;
t22 = -t17+t19+t20+t21;
t23 = tau(3.0);
t24 = t4.*t13;
t25 = d(3.0,3.0);
t26 = t3.*t25;
t27 = t2.*t16;
t28 = -t23+t24+t26+t27-t2.*t4.*t8;
Output = [t2+(Ts.*(tau(1.0)-t2.*d(1.0,1.0)+t3.*t16))./t8;t4-Ts.*(t6.*t12.*t22-t7.*t12.*t28);t3+Ts.*(t7.*t12.*t22-t5.*t12.*t28)];
